controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_trip:
        path: /api/trip
        controller: App\Controller\TripController::calculatePrice
